export { API_SCOPES, PLANNED_SCOPES, partnerScopeSchema, type PartnerScope } from './scopes.ts'
export {
  PARTNER_ERROR_STATUS,
  PARTNER_ERROR_CODES,
  partnerErrorCodeSchema,
  validationFailureSchema,
  partnerErrorSchema,
  COMMON_PARTNER_ERRORS,
  type PartnerErrorCode,
  type PartnerError,
} from './errors.ts'
export {
  API_KEY_ENVIRONMENTS,
  API_KEY_ID_LENGTH,
  API_KEY_ID_ALPHABET,
  formatApiKey,
  parseApiKey,
  bearerToken,
  type ApiKeyEnvironment,
  type ParsedApiKey,
} from './api-key.ts'
export {
  API_CLIENT_STATUSES,
  apiClientStatusSchema,
  API_KEY_DEFAULT_TTL_DAYS,
  API_KEY_MAX_TTL_DAYS,
  PATIENT_VERIFICATION_TTL_MINUTES,
  PATIENT_VERIFICATION_HEADER,
  VERIFICATION_LOCKOUT,
  PARTNER_RATE_LIMITS,
  ipAllowlistEntrySchema,
  apiClientSchema,
  createApiClientInput,
  PATIENT_VERIFICATION_METHODS,
  patientVerificationMethodSchema,
  patientVerificationSchema,
  type ApiClientStatus,
  type ApiClient,
  type CreateApiClientInput,
  type PatientVerificationMethod,
  type PatientVerification,
} from './api-client.ts'
export {
  PATIENT_LOOKUP_LIMIT,
  partnerPatientLookupInput,
  partnerPatientCandidateSchema,
  partnerPatientLookupOutput,
  partnerPatientParams,
  partnerVerifyPatientInput,
  partnerVerifyPatientOutput,
  type PartnerPatientLookupInput,
  type PatientLookupCriteria,
  type PartnerPatientCandidate,
  type PartnerPatientLookupOutput,
  type PartnerPatientParams,
  type PartnerVerifyPatientInput,
  type PartnerVerifyPatientOutput,
} from './patients.ts'
export {
  partnerQueueCountQuery,
  partnerQueueLocationCountSchema,
  partnerQueueCountOutput,
  type PartnerQueueCountQuery,
  type PartnerQueueCountOutput,
} from './queue.ts'
export {
  PARTNER_OPERATIONS,
  lookupPatientsOperation,
  verifyPatientOperation,
  queueCountOperation,
  documentedErrors,
  type PartnerOperation,
  type PartnerOperations,
  type PartnerOperationId,
  type PartnerOperationById,
} from './operations.ts'
export { buildPartnerOpenApiDocument, PARTNER_API_VERSION, PARTNER_API_BASE_PATH } from './openapi.ts'
